version: '3'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
     - "3010:3010"
     - "3011:3011"
  mariadb:
    build: 
        context: .
        dockerfile: Dockerfile.mariadb
    expose:
     - "3306"
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=dfohggioerhuoerhmgiodhgmi
    